<?php
ViewHelper\ViewHelperExtension::addExtensionClass([
    'ViewHelper\Extension\User',
    'ViewHelper\Extension\Page',
    'ViewHelper\Extension\Post',
    'Form\Form',
    'Pagination\Pagination',
    'App\Resource\Route',
    'Breadcrumbs\Breadcrumbs',
    'Module\Module',
    'Menu\Menu'
]);
